### ISSUE TITLE
can't claim funds

### ISSUE THREAD

**Issue by D3G3Nerator** [hackbg/smart-charity#16]
i am unable to claim funds after event

**Comment by imollov** [comment]
@ifunanya55 could you provide more details? Any error message?

**Comment by D3G3Nerator** [comment]
a payment splitter error

**Comment by D3G3Nerator** [comment]
MetaMask - RPC Error: execution reverted: PaymentSplitter: account is not due payment

**Comment by D3G3Nerator** [comment]
i also noticed that users will have to claim 1 - 3 times that's waste of gas xd

**Comment by imollov** [comment]
> MetaMask - RPC Error: execution reverted: PaymentSplitter: account is not due payment

@ifunanya55 Actually the error is correct - funds were transferred to you the first time you tried to claim: https://ropsten.etherscan.io/tx/0x73fa44d7e2ec9d8726466b2676a222b3d3bd5c43142f3206a143fce49bdc6e30.

Indeed, there are UX issues which caused the confusion and should be remedied by #10 and #15. 

Your suggestions as well as PRs are very welcome :)
